"""empty message

Revision ID: 8ddfef416860
Revises: b0114f8b991b
Create Date: 2024-03-25 09:49:48.912456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddfef416860'
down_revision = 'b0114f8b991b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
       op.add_column(sa.Column("email", sa.String(), nullable=False))
       op.create_unique_constraint("email", "users", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_constraint(None, "users", type_="unique")
        op.drop_column("users", "email")

    # ### end Alembic commands ###
