"""empty message

Revision ID: 99915e2cff7e
Revises: 3623235a66e7
Create Date: 2024-03-25 11:42:11.449605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99915e2cff7e'
down_revision = '3623235a66e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
